version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6.15
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: test
          command: npm test
      - run:
          name: code-coverage
          command: 'bash <(curl -s https://codecov.io/bash)'
